# Generated by Django 3.1.6 on 2021-02-23 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=48)),
                ("symbol", models.CharField(max_length=4)),
                ("code", models.CharField(max_length=3)),
            ],
            options={
                "verbose_name": "currency",
                "verbose_name_plural": "currencies",
                "db_table": "currency",
            },
        ),
        migrations.CreateModel(
            name="Territory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=48)),
                ("code_2", models.CharField(max_length=2)),
                ("code_3", models.CharField(max_length=3)),
                (
                    "local_currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dsrs.currency",
                    ),
                ),
            ],
            options={
                "verbose_name": "territory",
                "verbose_name_plural": "territories",
                "db_table": "territory",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="DSR",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=256)),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("failed", "FAILED"),
                            ("ingested", "INGESTED"),
                        ],
                        default="failed",
                        max_length=48,
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dsrs.currency",
                    ),
                ),
                (
                    "territory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dsrs.territory",
                    ),
                ),
            ],
            options={
                "db_table": "dsr",
            },
        ),
    ]
