# Generated by Django 3.1 on 2021-03-08 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dsrs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dsp_id', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=40)),
                ('artists', models.CharField(max_length=150)),
                ('isrc', models.CharField(max_length=20)),
                ('usages', models.IntegerField(default=0)),
                ('revenue', models.IntegerField(default=0)),
                ('dsrs', models.CharField(default=None, max_length=50)),
            ],
            options={
                'verbose_name': 'resource',
                'verbose_name_plural': 'resources',
                'db_table': 'resource',
            },
        ),
        migrations.AlterField(
            model_name='dsr',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dsrs', to='dsrs.currency'),
        ),
        migrations.AlterField(
            model_name='dsr',
            name='territory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dsrs', to='dsrs.territory'),
        ),
        migrations.AlterField(
            model_name='territory',
            name='local_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='territories', to='dsrs.currency'),
        ),
    ]
