# Generated by Django 3.1 on 2021-03-08 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsrs', '0003_auto_20210308_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='dsrs',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
