# Generated by Django 3.1 on 2021-03-08 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dsrs', '0004_auto_20210308_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='dsrs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dsrs', to='dsrs.dsr'),
        ),
    ]
