# Generated by Django 3.1 on 2021-03-08 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsrs', '0005_auto_20210308_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='dsrs',
            field=models.IntegerField(default=0),
        ),
    ]
