# Generated by Django 3.1 on 2021-03-09 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsrs', '0006_auto_20210309_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dsr',
            name='period_end',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='dsr',
            name='period_start',
            field=models.DateField(null=True),
        ),
    ]
