# Generated by Django 3.1 on 2021-03-09 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsrs', '0007_auto_20210309_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='artists',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='dsrs',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='isrc',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='revenue',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='title',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='usages',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
