# Generated by Django 3.1 on 2021-03-11 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dsrs', '0009_auto_20210309_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='dsrs',
        ),
        migrations.AddField(
            model_name='resource',
            name='dsr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dsr', to='dsrs.dsr'),
        ),
    ]
