# Generated by Django 3.1 on 2021-03-11 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dsrs', '0010_auto_20210311_1347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='dsr',
            new_name='dsrs',
        ),
    ]
