# Generated by Django 3.1 on 2021-03-11 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsrs', '0011_auto_20210311_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='dsrs',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
