# Generated by Django 3.1 on 2021-03-11 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dsrs', '0012_auto_20210311_1418'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='dsrs',
            new_name='dsrs_id',
        ),
    ]
